version: '3'

volumes:
  postgres_data:

services:
  postgres:
    image: library/postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "psql"
      POSTGRES_DB: "Ural"
    ports:
      - "1111:5432"